document.write(`<ul class="navbar cf">
            <li><a href="index.html">首页</a></li>
            <li><a href="kaifeng.html">开封</a></li>
            <li><a href="zhengzhou.html">郑州</a></li>
            <li><a href="luoyang.html">洛阳</a></li>
            <li><a href="anyang.html">安阳</a></li>
            <li><a href="xinxiang.html">新乡</a></li>
            <li><a href="jiaozuo.html">焦作</a></li>
            <li><a href="jiyuan.html">济源</a></li>
            <li><a href="puyang.html">濮阳</a></li>
            <li><a href="hebi.html">鹤壁</a></li>
            <li><a href="shangqiu.html">商丘</a></li>
            <li><a href="zhoukou.html">周口</a></li>
            <li><a href="xuchang.html">许昌</a></li>
            <li><a href="luohe.html">漯河</a></li>
            <li><a href="nanyang.html">南阳</a></li>
            <li><a href="xinyang.html">信阳</a></li>
            <li><a href="pingdingshan.html">平顶山</a></li>
            <li><a href="zhumadian.html">驻马店</a></li>
            <li><a href="sanmenxia.html">三门峡</a></li>
        </ul>`)